/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ILaunchpadInterface extends Interface {
    getFunction(nameOrSignature: "campaignCount" | "campaigns"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
  }

  

  export interface ILaunchpad extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILaunchpad;
    waitForDeployment(): Promise<this>;

    interface: ILaunchpadInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaigns: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean] & {creator: string, token: string, uniswapPair: string, targetAmount: bigint, amountRaised: bigint, deadline: bigint, reserveRatio: bigint, blockNumberCreated: bigint, isActive: boolean, isFundingComplete: boolean, isCancelled: boolean, isPromoted: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean] & {creator: string, token: string, uniswapPair: string, targetAmount: bigint, amountRaised: bigint, deadline: bigint, reserveRatio: bigint, blockNumberCreated: bigint, isActive: boolean, isFundingComplete: boolean, isCancelled: boolean, isPromoted: boolean }],
      'view'
    >;

    

    filters: {
      
    };
  }