/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IParentContract } from './IParentContract.js';
export type { LaunchpadV2 } from './LaunchpadV2.js';