/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LaunchpadV2Interface extends Interface {
    getFunction(nameOrSignature: "swapTokenForUsdc" | "uniswapFactory" | "uniswapRouter" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCancelled" | "RefundClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'swapTokenForUsdc', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'uniswapFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'uniswapRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'swapTokenForUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswapRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace CampaignCancelledEvent {
      export type InputTuple = [campaignId: BigNumberish, creator: AddressLike];
      export type OutputTuple = [campaignId: bigint, creator: string];
      export interface OutputObject {campaignId: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [campaignId: BigNumberish, investor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, investor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, investor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LaunchpadV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): LaunchpadV2;
    waitForDeployment(): Promise<this>;

    interface: LaunchpadV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    swapTokenForUsdc: TypedContractMethod<
      [_campaignId: BigNumberish, _tokenAmount: BigNumberish, _minUsdcOut: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    uniswapFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uniswapRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'swapTokenForUsdc'): TypedContractMethod<
      [_campaignId: BigNumberish, _tokenAmount: BigNumberish, _minUsdcOut: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uniswapFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uniswapRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CampaignCancelled'): TypedContractEvent<CampaignCancelledEvent.InputTuple, CampaignCancelledEvent.OutputTuple, CampaignCancelledEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;

    filters: {
      
      'CampaignCancelled(uint256,address)': TypedContractEvent<CampaignCancelledEvent.InputTuple, CampaignCancelledEvent.OutputTuple, CampaignCancelledEvent.OutputObject>;
      CampaignCancelled: TypedContractEvent<CampaignCancelledEvent.InputTuple, CampaignCancelledEvent.OutputTuple, CampaignCancelledEvent.OutputObject>;
    

      'RefundClaimed(uint256,address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    
    };
  }