/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IParentContract, IParentContractInterface } from "../../LaunchpadV2.sol/IParentContract.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "name": "_getCampaignInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "id",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "targetAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "amountRaised",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "tokensSold",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalSupply",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "tokensForSale",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "creatorAllocation",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "liquidityAllocation",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "platformFeeTokens",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "deadline",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "isActive",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "isFundingComplete",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "isCancelled",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "uint32",
            "name": "reserveRatio",
            "type": "uint32"
          },
          {
            "internalType": "uint256",
            "name": "blockNumberCreated",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "promotionalOgPoints",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isPromoted",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "uniswapPair",
            "type": "address"
          }
        ],
        "internalType": "struct CampaignInfo",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "campaignCount",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getSummaryStats",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "totalCampaigns",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "activeCampaigns",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "completedCampaigns",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "cancelledCampaigns",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "expiredCampaigns",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalFundingRaised",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IParentContract__factory {
    static readonly abi = _abi;
    static createInterface(): IParentContractInterface {
      return new Interface(_abi) as IParentContractInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IParentContract {
      return new Contract(address, _abi, runner) as unknown as IParentContract;
    }
  }
  