# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio
networks:
    - id: 296
      rpc: https://testnet.hashio.io/api
      start_block: 26400000
      contracts:
          - name: Launchpad
            address:
                - 0xCEadd06AE587CaD6eF922F91F18f26EB42180Bbb
            handler: src/EventHandlers.ts
            events:
                - event: CampaignCancelled(uint256 indexed campaignId, address indexed creator)
                - event: CampaignCreated(uint256 indexed campaignId, address indexed creator, string name, uint256 targetFunding, uint256 totalSupply, uint256 deadline)
                - event: CampaignPromoted(uint256 indexed campaignId)
                - event: FundingCompleted(uint256 indexed campaignId, uint256 totalFunding)
                - event: LiquidityAdded(uint256 indexed campaignId, uint256 usdcAmount, uint256 tokensAmount)
                - event: OgPointsAwarded(uint256 indexed campaignId, address indexed user, uint256 amount)
                - event: PlatformFeeUpdated(uint256 newFee)
                - event: RefundClaimed(uint256 indexed campaignId, address indexed investor, uint256 amount)
                - event: TokensPurchased(uint256 indexed campaignId, address indexed buyer, uint256 usdcAmount, uint256 tokensReceived, uint256 timestamp)
                - event: UserParticipatedInCampaign(uint256 indexed campaignId, address indexed user, uint256 amount)
          - name: LaunchpadV2
            address:
                - 0x928889FCfECEEE99eCd0D16176140D4714035D67
            handler: src/EventHandlers.ts
            events:
                - event: CampaignCancelled(uint256 indexed campaignId, address indexed creator)
                - event: LiquidityEvent(uint256 indexed campaignId, uint256 tokenAmount, uint256 usdcAmount, address user, uint8 tradeType, address token)
                - event: RefundClaimed(uint256 indexed campaignId, address indexed investor, uint256 amount)
                - event: SwapEvent(uint256 indexed campaignId, uint256 amount, address user, uint8 tradeType, address token)
          - name: Usdc
            address:
                - 0x82254d0f8C5091E79a5433f87ca7354a88FB1292
            handler: src/EventHandlers.ts
            events:
                - event: Approval(address indexed owner, address indexed spender, uint256 value)
                - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
                - event: Transfer(address indexed from, address indexed to, uint256 value)
          - name: CampaignDAOFactory
            address:
                - 0xb93719930F8f7a81ceF2B7D2B0717A5189993619
            handler: src/EventHandlers.ts
            events:
                - event: CampaignDAOCreated(uint256 indexed campaignId, address indexed campaignToken, address indexed daoAddress, address creator)
unordered_multichain_mode: true
preload_handlers: true
