/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUniswapV2Factory } from './IUniswapV2Factory.js';
export type { IUniswapV2Pair } from './IUniswapV2Pair.js';
export type { IUniswapV2Router } from './IUniswapV2Router.js';