/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IUniswapV2FactoryInterface extends Interface {
    getFunction(nameOrSignature: "allPairs" | "allPairsLength" | "createPair" | "feeTo" | "feeToSetter" | "getPair"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'allPairs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'allPairsLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'createPair', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'feeTo', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeToSetter', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPair', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allPairs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allPairsLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPair', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeToSetter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPair', data: BytesLike): Result;
  }

  

  export interface IUniswapV2Factory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUniswapV2Factory;
    waitForDeployment(): Promise<this>;

    interface: IUniswapV2FactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allPairs: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    allPairsLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createPair: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    feeTo: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    feeToSetter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPair: TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allPairs'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allPairsLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createPair'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeTo'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'feeToSetter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPair'): TypedContractMethod<
      [tokenA: AddressLike, tokenB: AddressLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }